// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjwhjmvgbzgzxgqrvdeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpqd2hqbXZnYnpnenhncXJ2ZGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NjU4MzcsImV4cCI6MjA2NjU0MTgzN30.S5gtOJ22u8bTxPdw4id4iwQ7nzemTeuf0GzYEtOn3W8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";


export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);


if (typeof window !== 'undefined') {
    (window as any).supabase = supabase;
}

